# Конфигурация сервера
server:
  host: "localhost"  # Хост, на котором будет запущен сервис
  port: 8080         # Порт, на котором будет запущен сервис

# Конфигурация базы данных
database:
  user: "your_db_user"       # Имя пользователя базы данных
  password: "your_db_password" # Пароль пользователя базы данных
  name: "your_db_name"       # Название базы данных
  host: "localhost"          # Хост базы данных
  port: 5432                 # Порт базы данных
  type: "postgres"           # Тип базы данных (например, postgres)